keys:
  - &admin_tassilo 91EBE87016391323642A6803B966009D57E69CC6
  - &admin_marcel 46D4682470DBE26790DF9433446F3B093DF81C6A
  - &doubleblind-science age1vuzm5rudzypmsx2a7ugnxrwzmppu4psdqn6lela7nazde99nv57s0wznk7
  - &postgres-hel1 age1weuzclujevy0z3nmxxta3v2d4dwsjxhd0gtmn8qzy3l3z2mpdy6svk23nt

creation_rules:
  - path_regex: secrets/doubleblind-science/secrets.yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_marcel
        age:
        - *doubleblind-science

  - path_regex: secrets/postgres-hel1/secrets.yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_marcel
        age:
        - *postgres-hel1
  
