keys:
  - &admin_tassilo 91EBE87016391323642A6803B966009D57E69CC6
  - &admin_marcel 46D4682470DBE26790DF9433446F3B093DF81C6A
  - &dresden-zone age18vkl5lry74xm6xme54jpwc0w2efr4z8g7d8twvszyxxmuw5dqf6qh5lruh
creation_rules:
  - path_regex: secrets/dresden-zone/[^/]+\.yaml$
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_marcel
        age:
        - *dresden-zone
  
